Added snyk security code to workflow

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -11,15 +11,46 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: Install & Run Gitleaks
         run: |
           sudo apt-get update
           sudo apt-get install -y gitleaks
           gitleaks detect --source . --report-format json --report-path=gitleaks-report.json
 
+  security-scan-synk:
+    runs-on: ubuntu-latest
+    needs: security-scan-gitleaks
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/dotnet@master
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          command: code test
+          args: --sarif-file-output=snyk.sarif
+
+      - name: Count total number of vulnerabilities
+        run: |
+          RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
+          echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
+          echo $RESULTS_LENGTH
+
+      - name: Pass_or_Fail_the_job
+        run: |
+            if [ "$RESULTS_LENGTH" != 0 ]; then
+                echo "Job Failed"
+                exit 1
+            else
+                echo "Pass"
+            fi        
+
   build:
     runs-on: ubuntu-latest
-    needs: [security-scan-gitleaks]
+    needs: [security-scan-synk]
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
